---
title: "Important LaTeX bits"
author: "A Solomon Kurz"
date: "`r format(Sys.Date())`"
output:
  github_document
---

# What's the deal?

Offering the project in both HTML and PDF versions presents difficulties with some of the [LaTeX](https://www.latex-project.org) code. The issue stems from underscores. In some of the mathematical formulas in the project, one or more of the variables include underscores within the name. For example, the equation in section 5.1.1 contains two predictors, `Marriage_s` and `MedianAgeMarriage_s`. Both names end in the suffix `_s`. This doesn’t cause any problems when rendering to HTML. For example, the pertinent line of LaTeX is 

\\mu_i & = \\alpha + \\beta_1 \\text{Marriage_s}_i + \\beta_2 \\text{MedianAgeMarriage_s}_i

It renders beautifully. However, those `_1` suffixes produce errors when attempting to render to PDF. In that situation, the solution is to insert a backslash before the two underscores. It looks like this: 

\\mu_i & = \\alpha + \\beta_1 \\text{Marriage\_s}_i + \\beta_2 \\text{MedianAgeMarriage\\_s}_i

When rendering to PDF, it works like a dream. However, when rendering to HTML, those extra backslashes get rendered as if there were part of the variable names. It’s a disaster. So the current fix is to document every place in the project including LaTeX syntax involving variable names including underscores. Happily, this only effects the `.Rmd` files for chapters 5, 7, 10, 12, and 13. Below I document each relevant section from each document with its line number.

# How do I use this document?

The GitHub rendered version of this document (i.e., the `.md` file) is useful for understanding the problem. However, the rendering complications limit its utility for seeing the offending LaTeX code. For that, you’re probably best off checking out the `.Rmd` file.

## Chapter 05

line 214

\begin{align*}
\text{Divorce}_i & \sim \text{Normal}(\mu_i, \sigma) \\
\mu_i & = \alpha + \beta_1 \text{Marriage\_s}_i + \beta_2 \text{MedianAgeMarriage\_s}_i \\
\alpha & \sim \text{Normal}(10, 10) \\
\beta_1 & \sim \text{Normal}(0, 1) \\
\beta_2 & \sim \text{Normal}(0, 1) \\
\sigma & \sim \text{Uniform}(0, 10)
\end{align*}

line 1591

$$
\mu_i = \alpha + \beta_\text{clade\_nwm} \text{clade\_nwm}_i + \beta_\text{clade\_owm} \text{clade\_owm}_i + \beta_\text{clade\_s} \text{clade\_s}_i + \beta_\text{perc.fat} \text{perc.fat}_i
$$

## Chapter 07

line 218

\begin{align*}
\text{log\_gdp}_i & \sim \text{Normal} (\mu_i, \sigma) \\
\mu_i    & = \alpha + \gamma_i \text{rugged}_i + \beta_2 \text{cont\_africa}_i \\
\gamma_i & = \beta_1 + \beta_3 \text{cont\_africa}_i
\end{align*}

line 262

\begin{align*}
\text{log\_gdp}_i & \sim \text{Normal} (\mu_i, \sigma) \\
\mu_i & = \alpha + \beta_1 \text{rugged}_i + \beta_2 \text{cont\_africa}_i + \beta_3 \text{rugged}_i \times \text{cont\_africa}_i
\end{align*}

line 409

\begin{align*}
\text{log\_gdp}_i & \sim \text{Normal} (\mu_i, \sigma) \\
\mu_i    & = \alpha + \gamma_i \text{rugged}_i + \beta_2 \text{cont\_africa}_i \\
\gamma_i & = \beta_1 + \beta_3 \text{cont\_africa}_i
\end{align*}

line 417

\begin{align*}
\mu_i & = \alpha + (\beta_1 + \beta_3 \text{cont\_africa}_i) \times \text{rugged}_i + \beta_2 \text{cont\_africa}_i \\
      & = \alpha + \beta_1 \text{rugged}_i + \beta_3 \text{rugged}_i \times \text{cont\_africa}_i + \beta_2 \text{cont\_africa}_i
\end{align*}

line 424

$$
\mu_i = \alpha + \beta_1 \text{rugged}_i + \underbrace{(\beta_2 + \beta_3 \text{rugged}_i)}_G \times \text{cont\_africa}_i
$$

## Chapter 10

line 51

\begin{align*}
\text{pulled\_left}_i & \sim \text{Binomial} (1, p_i) \\
\text{logit} (p_i)    & = \alpha \\
\alpha                & \sim \text{Normal} (0, 10)
\end{align*}

line 265

\begin{align*}
\text{pulled\_left}_i & \sim \text{Binomial} (1, p_i) \\
\text{logit} (p_i)    & = \alpha_{\text{actor}} + (\beta_1 + \beta_2 \text{condition}_i) \text{prosoc\_left}_i \\
\alpha_{\text{actor}} & \sim \text{Normal} (0, 10) \\
\beta_1               & \sim \text{Normal} (0, 10) \\
\beta_2               & \sim \text{Normal} (0, 10)
\end{align*}

line 864

\begin{align*}
\text{total\_tools}_i   & \sim \text{Poisson} (\lambda_i) \\
\text{log} (\lambda_i) & = \alpha + \beta_1 \text{log\_pop}_i + \beta_2 \text{contact\_high}_i + \beta_3 \text{contact\_high}_i \times \text{log\_pop}_i \\
\alpha  & \sim \text{Normal} (0, 100) \\
\beta_1 & \sim \text{Normal} (0, 1) \\
\beta_2 & \sim \text{Normal} (0, 1) \\
\beta_3 & \sim \text{Normal} (0, 1)
\end{align*}

## Chapter 12

line 542

\begin{align*}
\text{left\_pull}_i   & \sim \text{Binomial} (n_i = 1, p_i) \\
\text{logit} (p_i)    & = \alpha + \alpha_{\text{actor}_i} + (\beta_1 + \beta_2 \text{condition}_i) \text{prosoc\_left}_i \\
\alpha_{\text{actor}} & \sim \text{Normal} (0, \sigma_{\text{actor}}) \\
\alpha                & \sim \text{Normal} (0, 10) \\
\beta_1               & \sim \text{Normal} (0, 10) \\
\beta_2               & \sim \text{Normal} (0, 10) \\
\sigma_{\text{actor}} & \sim \text{HalfCauchy} (0, 1)
\end{align*}

line 649

\begin{align*}
\text{left\_pull}_i   & \sim \text{Binomial} (n_i = 1, p_i) \\
\text{logit} (p_i)    & = \alpha + \alpha_{\text{actor}_i} + \alpha_{\text{block}_i} + (\beta_1 + \beta_2 \text{condition}_i) \text{prosoc\_left}_i \\
\alpha_{\text{actor}} & \sim \text{Normal} (0, \sigma_{\text{actor}}) \\
\alpha_{\text{block}} & \sim \text{Normal} (0, \sigma_{\text{actor}}) \\
\alpha                & \sim \text{Normal} (0, 10) \\
\beta_1               & \sim \text{Normal} (0, 10) \\
\beta_2               & \sim \text{Normal} (0, 10) \\
\sigma_{\text{actor}} & \sim \text{HalfCauchy} (0, 1) \\
\sigma_{\text{block}} & \sim \text{HalfCauchy} (0, 1)
\end{align*}

line 1159

\begin{align*}
\text{total\_tools}_i    & \sim \text{Poisson} (\mu_i) \\
\text{log} (\mu_i)      & = \alpha + \alpha_{\text{culture}_i} + \beta \text{log} (\text{population}_i) \\
\alpha                  & \sim \text{Normal} (0, 10) \\
\beta                   & \sim \text{Normal} (0, 1) \\
\alpha_{\text{culture}} & \sim \text{Normal} (0, \sigma_{\text{culture}}) \\
\sigma_{\text{culture}} & \sim \text{HalfCauchy} (0, 1) \\
\end{align*}

line 1259

\begin{align*}
\text{pulled\_left}_i  & \sim \text{Binomial} (n_i = 1, p_i) \\
\text{logit} (p_i)    & = \alpha + \alpha_{\text{actor}_i}\\
\alpha                & \sim \text{Normal} (0, 10) \\
\alpha_{\text{actor}} & \sim \text{Normal} (0, \sigma_{\text{actor}}) \\
\sigma_{\text{actor}} & \sim \text{HalfCauchy} (0, 1)
\end{align*}

line 1308

\begin{align*}
\text{pulled\_left}_i  & \sim \text{Binomial} (n_i = 1, p_i) \\
\text{logit} (p_i)    & = \alpha + \alpha_{\text{actor}_i} + \alpha_{\text{block}_i}\\
\alpha                & \sim \text{Normal} (0, 10) \\
\alpha_{\text{actor}} & \sim \text{Normal} (0, \sigma_{\text{actor}}) \\
\alpha_{\text{block}} & \sim \text{Normal} (0, \sigma_{\text{block}}) \\
\sigma_{\text{actor}} & \sim \text{HalfCauchy} (0, 1) \\
\sigma_{\text{block}} & \sim \text{HalfCauchy} (0, 1)
\end{align*}

## Chapter 13

line 425

\begin{align*}
\text{admit}_i         & \sim \text{Binomial} (n_i, p_i) \\
\text{logit} (p_i)     & = \alpha_{\text{dept\_id}_i} + \beta \text{male}_i \\
\alpha_\text{dept\_id} & \sim \text{Normal} (\alpha, \sigma) \\
\alpha                 & \sim \text{Normal} (0, 10) \\
\beta                  & \sim \text{Normal} (0, 1) \\
\sigma                 & \sim \text{HalfCauchy} (0, 2) \\
\end{align*}

line 527

\begin{align*}
\text{admit}_i     & \sim \text{Binomial} (n_i, p_i) \\
\text{logit} (p_i) & = \alpha_{\text{dept\_id}_i} + \beta_{\text{dept\_id}_i} \text{male}_i \\
\begin{bmatrix} \alpha_\text{dept\_id} \\ \beta_\text{dept\_id} \end{bmatrix} & \sim \text{MVNormal} \bigg (\begin{bmatrix} \alpha \\ \beta \end{bmatrix}, \mathbf{S}  \bigg ) \\
\mathbf S & = \begin{pmatrix} \sigma_\alpha & 0 \\ 0 & \sigma_\beta \end{pmatrix} \mathbf R \begin{pmatrix} \sigma_\alpha & 0 \\ 0 & \sigma_\beta \end{pmatrix} \\
\alpha                        & \sim \text{Normal} (0, 10) \\
\beta                         & \sim \text{Normal} (0, 1) \\
(\sigma_\alpha, \sigma_\beta) & \sim \text{HalfCauchy} (0, 2) \\
\mathbf R                     & \sim \text{LKJcorr} (2)
\end{align*}

line 778

\begin{align*}
\text{pulled\_left}_i      & \sim \text{Binomial} (n = 1, p_i) \\
\text{logit} (p_i)         & = \alpha_i + (\beta_{1i} + \beta_{2i} \text{condition}_i) \text{prosoc\_left}_i  \\
\alpha_i                   & = \alpha + \alpha_{\text{actor}_i} + \alpha_{\text{block\_id}_i} \\
\beta_{1i}                 & = \beta_1 + \beta_{1, \text{actor}_i} + \beta_{1, \text{block\_id}_i} \\
\beta_{2i}                 & = \beta_2 + \beta_{2, \text{actor}_i} + \beta_{2, \text{block\_id}_i} \\
\begin{bmatrix} \alpha_\text{actor} \\ \beta_{1, \text{actor}} \\ \beta_{2, \text{actor}} \end{bmatrix} & \sim \text{MVNormal} \begin{pmatrix} \begin{bmatrix}0 \\ 0 \\ 0 \end{bmatrix} , \mathbf{S}_\text{actor} \end{pmatrix} \\
\begin{bmatrix} \alpha_\text{block\_id} \\ \beta_{1, \text{block\_id}} \\ \beta_{2, \text{block\_id}} \end{bmatrix} & \sim \text{MVNormal} \begin{pmatrix} \begin{bmatrix}0 \\ 0 \\ 0 \end{bmatrix} , \mathbf{S}_\text{block\_id} \end{pmatrix} \\
\mathbf S_\text{actor}     & = \begin{pmatrix} \sigma_{\alpha_\text{actor}} & 0 & 0 \\ 0 & \sigma_{\beta_{1_\text{actor}}} & 0 \\ 0 & 0 & \sigma_{\beta_{2_\text{actor}}} \end{pmatrix} 
\mathbf R_\text{actor} \begin{pmatrix} \sigma_{\alpha_\text{actor}} & 0 & 0 \\ 0 & \sigma_{\beta_{1_\text{actor}}} & 0 \\ 0 & 0 & \sigma_{\beta_{2_\text{actor}}} \end{pmatrix} \\
\mathbf S_\text{block\_id} & = \begin{pmatrix} \sigma_{\alpha_\text{block\_id}} & 0 & 0 \\ 0 & \sigma_{\beta_{1_\text{block\_id}}} & 0 \\ 0 & 0 & \sigma_{\beta_{2_\text{block\_id}}} \end{pmatrix} 
\mathbf R_\text{block\_id} \begin{pmatrix} \sigma_{\alpha_\text{block\_id}} & 0 & 0 \\ 0 & \sigma_{\beta_{1_\text{block\_id}}} & 0 \\ 0 & 0 & \sigma_{\beta_{2_\text{block\_id}}} \end{pmatrix} \\
\alpha                     & \sim \text{Normal} (0, 1) \\
\beta_1                    & \sim \text{Normal} (0, 1) \\
\beta_2                    & \sim \text{Normal} (0, 1) \\
(\sigma_{\alpha_\text{actor}}, \sigma_{\beta_{1_\text{actor}}}, \sigma_{\beta_{2_\text{actor}}}) & \sim \text{HalfCauchy} (0, 2) \\
(\sigma_{\alpha_\text{block\_id}}, \sigma_{\beta_{1_\text{block\_id}}}, \sigma_{\beta_{2_\text{block\_id}}}) & \sim \text{HalfCauchy} (0, 2) \\
\mathbf R_\text{actor}     & \sim \text{LKJcorr} (4) \\
\mathbf R_\text{block\_id} & \sim \text{LKJcorr} (4)
\end{align*}

## Session info

```{r}
sessionInfo()
```
